services:

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    environment:
      - TZ=America/New_York
    networks:
      - cloudflare_tunnel
    restart: unless-stopped
    pull_policy: always

networks:
  cloudflare_tunnel:
    external: true
