services:

  unpoller:
    restart: always
    container_name: unpoller
    image: ghcr.io/unpoller/unpoller:latest
    networks:
      - monitoring
    pull_policy: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UP_UNIFI_DEFAULT_SAVE_SITES=true
      - UP_UNIFI_DEFAULT_SAVE_DPI=true
      - UP_INFLUXDB_DISABLE=true
      - UP_UNIFI_DEFAULT_USER=${UNIFI_USER}
      - UP_UNIFI_DEFAULT_PASS=${UNIFI_PASS}
      - UP_UNIFI_DEFAULT_URL=${UNIFI_URL}

networks:
  monitoring:
    external: true